                              List of relations
 Schema |                     Name                     |   Type   |  Owner   
--------+----------------------------------------------+----------+----------
 public | application_masters_appcontent               | table    | postgres
 public | application_masters_appcontent_id_seq        | sequence | postgres
 public | application_masters_category                 | table    | postgres
 public | application_masters_category_id_seq          | sequence | postgres
 public | application_masters_comorbid                 | table    | postgres
 public | application_masters_comorbid_id_seq          | sequence | postgres
 public | application_masters_district                 | table    | postgres
 public | application_masters_district_id_seq          | sequence | postgres
 public | application_masters_dosage                   | table    | postgres
 public | application_masters_dosage_id_seq            | sequence | postgres
 public | application_masters_masterlookup             | table    | postgres
 public | application_masters_masterlookup_id_seq      | sequence | postgres
 public | application_masters_medicines                | table    | postgres
 public | application_masters_medicines_id_seq         | sequence | postgres
 public | application_masters_phc                      | table    | postgres
 public | application_masters_phc_id_seq               | sequence | postgres
 public | application_masters_state                    | table    | postgres
 public | application_masters_state_id_seq             | sequence | postgres
 public | application_masters_subcenter                | table    | postgres
 public | application_masters_subcenter_id_seq         | sequence | postgres
 public | application_masters_taluk                    | table    | postgres
 public | application_masters_taluk_id_seq             | sequence | postgres
 public | application_masters_village                  | table    | postgres
 public | application_masters_village_id_seq           | sequence | postgres
 public | auth_group                                   | table    | postgres
 public | auth_group_id_seq                            | sequence | postgres
 public | auth_group_permissions                       | table    | postgres
 public | auth_group_permissions_id_seq                | sequence | postgres
 public | auth_permission                              | table    | postgres
 public | auth_permission_id_seq                       | sequence | postgres
 public | auth_user                                    | table    | postgres
 public | auth_user_groups                             | table    | postgres
 public | auth_user_groups_id_seq                      | sequence | postgres
 public | auth_user_id_seq                             | sequence | postgres
 public | auth_user_user_permissions                   | table    | postgres
 public | auth_user_user_permissions_id_seq            | sequence | postgres
 public | django_admin_log                             | table    | postgres
 public | django_admin_log_id_seq                      | sequence | postgres
 public | django_content_type                          | table    | postgres
 public | django_content_type_id_seq                   | sequence | postgres
 public | django_migrations                            | table    | postgres
 public | django_migrations_id_seq                     | sequence | postgres
 public | django_session                               | table    | postgres
 public | health_management_diagnosis                  | table    | postgres
 public | health_management_diagnosis_id_seq           | sequence | postgres
 public | health_management_drugdispensation           | table    | postgres
 public | health_management_drugdispensation_id_seq    | sequence | postgres
 public | health_management_homevisit                  | table    | postgres
 public | health_management_homevisit_id_seq           | sequence | postgres
 public | health_management_medicinestock              | table    | postgres
 public | health_management_medicinestock_id_seq       | sequence | postgres
 public | health_management_patients                   | table    | postgres
 public | health_management_patients_id_seq            | sequence | postgres
 public | health_management_prescription               | table    | postgres
 public | health_management_prescription_id_seq        | sequence | postgres
 public | health_management_scanned_report             | table    | postgres
 public | health_management_scanned_report_id_seq      | sequence | postgres
 public | health_management_treatments                 | table    | postgres
 public | health_management_treatments_id_seq          | sequence | postgres
 public | health_management_userprofile                | table    | postgres
 public | health_management_userprofile_id_seq         | sequence | postgres
 public | health_management_userprofile_village        | table    | postgres
 public | health_management_userprofile_village_id_seq | sequence | postgres
(63 rows)

