# Generated by Django 3.2.6 on 2022-12-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_masters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='village',
            options={'verbose_name_plural': 'Village'},
        ),
        migrations.AlterField(
            model_name='appcontent',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='district',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='phc',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='state',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='taluk',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='village',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'active')], db_index=True, default=2),
        ),
        migrations.AlterUniqueTogether(
            name='village',
            unique_together={('name', 'phc')},
        ),
    ]
