# Generated by Django 3.2.6 on 2022-12-09 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application_masters', '0003_auto_20221208_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterlookup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdapplication_masters_masterlookup_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='masterlookup',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifiedapplication_masters_masterlookup_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='masterlookup',
            name='server_created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masterlookup',
            name='server_modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='masterlookup',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active')], db_index=True, default=2),
        ),
        migrations.AddField(
            model_name='masterlookup',
            name='uuid',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True, unique=True),
        ),
    ]
