# Generated by Django 3.2.6 on 2022-12-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_masters', '0004_auto_20221209_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='parent_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
