# Generated by Django 3.2.6 on 2022-12-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_masters', '0005_state_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcontent',
            name='sync_status',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='district',
            name='sync_status',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='masterlookup',
            name='sync_status',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='phc',
            name='sync_status',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='state',
            name='sync_status',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='taluk',
            name='sync_status',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='village',
            name='sync_status',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
