# Generated by Django 3.2.6 on 2022-12-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_masters', '0010_dosage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dosage',
            options={'verbose_name_plural': 'Dosage'},
        ),
        migrations.AddField(
            model_name='district',
            name='code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='taluk',
            name='code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
