# Generated by Django 3.2.6 on 2022-12-19 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_masters', '0012_subcenter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phc',
            old_name='phc_code',
            new_name='code',
        ),
    ]
