# Generated by Django 3.2.6 on 2022-12-19 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_masters', '0013_rename_phc_code_phc_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='subcenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application_masters.subcenter'),
        ),
        migrations.AlterUniqueTogether(
            name='village',
            unique_together={('name', 'subcenter')},
        ),
        migrations.RemoveField(
            model_name='village',
            name='phc',
        ),
    ]
