# Generated by Django 3.2.6 on 2023-01-17 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_masters', '0015_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='village',
            options={'ordering': ['subcenter'], 'verbose_name_plural': 'Village'},
        ),
    ]
