# Generated by Django 4.1.7 on 2023-03-14 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_masters', '0019_remove_medicines_category_id_medicines_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicines',
            old_name='type',
            new_name='medicines_type',
        ),
    ]
