# Generated by Django 3.2.6 on 2022-12-07 13:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application_masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, editable=False, max_length=200, null=True, unique=True)),
                ('status', models.PositiveIntegerField(choices=[(0, 'Inactive'), (1, 'active')], db_index=True, default=1)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('types', models.CharField(blank=True, max_length=50, null=True)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdhealth_management_medicines_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifiedhealth_management_medicines_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Treatments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Inactive'), (1, 'active')], db_index=True, default=1)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(blank=True, max_length=150, null=True)),
                ('patient_uuid', models.CharField(blank=True, max_length=150, null=True)),
                ('visit_date', models.DateTimeField(blank=True, null=True)),
                ('bp_sys1', models.CharField(blank=True, max_length=150, null=True)),
                ('bp_non_sys1', models.CharField(blank=True, max_length=150, null=True)),
                ('bp_sys2', models.CharField(blank=True, max_length=150, null=True)),
                ('bp_non_sys2', models.CharField(blank=True, max_length=150, null=True)),
                ('bp_sys3', models.CharField(blank=True, max_length=150, null=True)),
                ('bp_non_sys3', models.CharField(blank=True, max_length=150, null=True)),
                ('fbs', models.CharField(blank=True, max_length=150, null=True)),
                ('pp', models.CharField(blank=True, max_length=150, null=True)),
                ('random', models.CharField(blank=True, max_length=150, null=True)),
                ('weight', models.CharField(blank=True, max_length=150, null=True)),
                ('bmi', models.CharField(blank=True, max_length=150, null=True)),
                ('symptoms', models.CharField(blank=True, max_length=150, null=True)),
                ('remarks', models.CharField(blank=True, max_length=150, null=True)),
                ('hyper_diabetic', models.PositiveIntegerField(blank=True, null=True)),
                ('co_morbid_ids', models.CharField(blank=True, max_length=150, null=True)),
                ('co_morbid_names', models.CharField(blank=True, max_length=150, null=True)),
                ('is_alcoholic', models.IntegerField(blank=True, null=True)),
                ('is_tobacco', models.IntegerField(blank=True, null=True)),
                ('is_smoker', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdhealth_management_treatments_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifiedhealth_management_treatments_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scanned_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Inactive'), (1, 'active')], db_index=True, default=1)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(blank=True, max_length=150, null=True)),
                ('patient_uuid', models.CharField(blank=True, max_length=150, null=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('image_path', models.CharField(blank=True, max_length=150, null=True)),
                ('captured_date', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.IntegerField(default=2)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdhealth_management_scanned_report_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifiedhealth_management_scanned_report_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Inactive'), (1, 'active')], db_index=True, default=1)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(blank=True, max_length=150, null=True)),
                ('patient_uuid', models.CharField(blank=True, max_length=150, null=True)),
                ('treatment_uuid', models.CharField(blank=True, max_length=150, null=True)),
                ('dosage', models.CharField(blank=True, max_length=150, null=True)),
                ('no_of_days', models.IntegerField(blank=True, null=True)),
                ('medicine_type', models.CharField(blank=True, max_length=150, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('sync_status', models.IntegerField(default=2)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdhealth_management_prescription_related', to=settings.AUTH_USER_MODEL)),
                ('medicines', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='health_management.medicines')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifiedhealth_management_prescription_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Inactive'), (1, 'active')], db_index=True, default=1)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(blank=True, max_length=150, null=True)),
                ('patient_uuid', models.CharField(blank=True, max_length=150, null=True)),
                ('name', models.CharField(max_length=150)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], null=True)),
                ('phone_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits', regex='\\d{10}$')])),
                ('image', models.FileField(blank=True, null=True, upload_to='patients_image/%y/%m/%d/')),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('door_no', models.CharField(blank=True, max_length=150, null=True)),
                ('fee_status', models.PositiveIntegerField(blank=True, null=True)),
                ('fee_paid', models.PositiveIntegerField(blank=True, null=True)),
                ('fee_date', models.DateTimeField(blank=True, null=True)),
                ('registered_date', models.DateTimeField(blank=True, null=True)),
                ('last_visit_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdhealth_management_patients_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifiedhealth_management_patients_related', to=settings.AUTH_USER_MODEL)),
                ('patient_visit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application_masters.masterlookup')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application_masters.village')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Inactive'), (1, 'active')], db_index=True, default=1)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(blank=True, max_length=150, null=True)),
                ('treatment_uuid', models.CharField(blank=True, max_length=150, null=True)),
                ('source_treatment', models.IntegerField(blank=True, null=True)),
                ('years', models.IntegerField(blank=True, null=True)),
                ('sync_status', models.IntegerField(default=2)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdhealth_management_diagnosis_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifiedhealth_management_diagnosis_related', to=settings.AUTH_USER_MODEL)),
                ('ndc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application_masters.masterlookup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comorbid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, editable=False, max_length=200, null=True, unique=True)),
                ('status', models.PositiveIntegerField(choices=[(0, 'Inactive'), (1, 'active')], db_index=True, default=1)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdhealth_management_comorbid_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifiedhealth_management_comorbid_related', to=settings.AUTH_USER_MODEL)),
                ('patients', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='health_management.patients')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
