# Generated by Django 3.2.6 on 2022-12-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='sync_status',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='treatments',
            name='sync_status',
            field=models.IntegerField(default=2),
        ),
    ]
