# Generated by Django 3.2.6 on 2022-12-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0002_auto_20221207_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comorbid',
            options={'verbose_name_plural': 'Comorbid'},
        ),
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'verbose_name_plural': 'Diagnosis'},
        ),
        migrations.AlterModelOptions(
            name='medicines',
            options={'verbose_name_plural': 'Medicines'},
        ),
        migrations.AlterModelOptions(
            name='patients',
            options={'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'verbose_name_plural': 'Prescription'},
        ),
        migrations.AlterModelOptions(
            name='scanned_report',
            options={'verbose_name_plural': 'Scanned Report'},
        ),
        migrations.AlterModelOptions(
            name='treatments',
            options={'verbose_name_plural': 'Treatments'},
        ),
        migrations.AlterField(
            model_name='comorbid',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='patients',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='scanned_report',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'active')], db_index=True, default=2),
        ),
    ]
