# Generated by Django 3.2.6 on 2022-12-08 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application_masters', '0002_auto_20221208_0713'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health_management', '0003_auto_20221208_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'active')], db_index=True, default=2)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=200, null=True, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=450, null=True)),
                ('user_type', models.PositiveIntegerField(choices=[(1, 'Health worker'), (2, 'Doctor')], db_index=True, default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdhealth_management_userprofile_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifiedhealth_management_userprofile_related', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application_masters.village')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
