# Generated by Django 3.2.6 on 2022-12-08 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0004_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='full_name',
            new_name='name',
        ),
    ]
