# Generated by Django 3.2.6 on 2022-12-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0005_rename_full_name_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
