# Generated by Django 3.2.6 on 2022-12-08 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0006_userprofile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='patient_uuid',
            new_name='patient_id',
        ),
    ]
