# Generated by Django 3.2.6 on 2022-12-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0007_rename_patient_uuid_patients_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comorbid',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='patients',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='scanned_report',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active')], db_index=True, default=2),
        ),
    ]
