# Generated by Django 3.2.6 on 2022-12-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0008_auto_20221208_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='detected_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
