# Generated by Django 3.2.6 on 2022-12-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0009_diagnosis_detected_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='comorbid',
            name='sync_status',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='medicines',
            name='sync_status',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sync_status',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
