# Generated by Django 3.2.6 on 2022-12-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0010_auto_20221212_0724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comorbid',
            name='patients',
        ),
        migrations.AddField(
            model_name='comorbid',
            name='patient_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
