# Generated by Django 3.2.6 on 2022-12-12 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0011_auto_20221212_1153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comorbid',
        ),
    ]
