# Generated by Django 3.2.6 on 2022-12-13 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_masters', '0008_medicines'),
        ('health_management', '0012_delete_comorbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='medicines',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application_masters.medicines'),
        ),
        migrations.DeleteModel(
            name='Medicines',
        ),
    ]
