# Generated by Django 3.2.6 on 2022-12-20 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0017_patients_seq_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits', regex='\\d{10}$')]),
        ),
    ]
