# Generated by Django 3.2.6 on 2022-12-22 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_masters', '0014_auto_20221219_1319'),
        ('health_management', '0018_alter_patients_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application_masters.village'),
        ),
    ]
