# Generated by Django 3.2.6 on 2022-12-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0020_patients_subcenter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_no',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
