# Generated by Django 3.2.6 on 2022-12-28 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health_management', '0021_userprofile_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active')], db_index=True, default=2)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('sync_status', models.PositiveIntegerField(default=2)),
                ('uuid', models.CharField(blank=True, max_length=150, null=True)),
                ('patient_uuid', models.CharField(blank=True, max_length=150, null=True)),
                ('home_vist', models.PositiveIntegerField(choices=[(1, 'Yes'), (2, 'No')], default=0)),
                ('response_location', models.CharField(blank=True, max_length=150, null=True)),
                ('response_datetime', models.DateTimeField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='home_visit_image/%y/%m/%d/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdhealth_management_homevisit_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifiedhealth_management_homevisit_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
