# Generated by Django 3.2.6 on 2022-12-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0022_homevisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homevisit',
            name='home_vist',
            field=models.PositiveIntegerField(choices=[(1, 'No'), (2, 'Yes')], default=0),
        ),
    ]
