# Generated by Django 3.2.6 on 2023-01-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0024_drugdispensation_medicinestock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinestock',
            name='date_of_creation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DrugDispensation',
        ),
    ]
