# Generated by Django 3.2.6 on 2023-01-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0026_drugdispensation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugdispensation',
            name='date_of_dispensation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
