# Generated by Django 3.2.6 on 2023-01-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0027_alter_drugdispensation_date_of_dispensation'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='user_uuid',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='homevisit',
            name='user_uuid',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='user_uuid',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='scanned_report',
            name='user_uuid',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='treatments',
            name='user_uuid',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
