# Generated by Django 3.2.6 on 2023-01-17 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0028_auto_20230117_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
