# Generated by Django 3.2.6 on 2023-01-17 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_masters', '0016_alter_village_options'),
        ('health_management', '0030_auto_20230117_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application_masters.village'),
        ),
    ]
