# Generated by Django 3.2.6 on 2023-01-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0031_alter_userprofile_village'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='user_uuid',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
