# Generated by Django 3.2.6 on 2023-01-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_masters', '0016_alter_village_options'),
        ('health_management', '0032_patients_user_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='village',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='village',
            field=models.ManyToManyField(blank=True, to='application_masters.Village'),
        ),
    ]
