# Generated by Django 3.2.6 on 2023-01-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0033_auto_20230123_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='homevisit',
            name='image_location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
