# Generated by Django 3.2.6 on 2023-02-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0035_villageprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='villageprofile',
            name='code',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='villageprofile',
            name='house_hold',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='villageprofile',
            name='individual',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='villageprofile',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
