# Generated by Django 3.2.6 on 2023-02-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0036_auto_20230224_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villageprofile',
            name='code',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
