# Generated by Django 4.1.7 on 2023-04-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0040_remove_villageprofile_aadhar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='villageprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='villageprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='villageprofile',
            name='door_no',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='villageprofile',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], null=True),
        ),
        migrations.AddField(
            model_name='villageprofile',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='villageprofile',
            name='patient_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='villageprofile',
            name='seq_no',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='villageprofile',
            name='subcenter_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
