# Generated by Django 4.1.7 on 2023-04-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0042_villageprofile_image_villageprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatments',
            name='is_controlled',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True),
        ),
    ]
