# Generated by Django 4.1.7 on 2023-04-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0043_treatments_is_controlled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villageprofile',
            name='patient_id',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
