# Generated by Django 4.1.7 on 2023-04-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0044_alter_villageprofile_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villageprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
