# Generated by Django 4.1.7 on 2023-04-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0045_alter_villageprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='villageprofile',
            name='data_migration',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
