# Generated by Django 4.1.7 on 2023-04-19 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health_management', '0046_villageprofile_data_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, editable=False, max_length=200, null=True, unique=True)),
                ('status', models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active')], db_index=True, default=2)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('sync_status', models.PositiveIntegerField(default=2)),
                ('code', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('htn', models.IntegerField(blank=True, null=True)),
                ('detected_by_htn', models.IntegerField(blank=True, null=True)),
                ('detected_since_htn', models.IntegerField(blank=True, null=True)),
                ('dm', models.IntegerField(blank=True, null=True)),
                ('detected_by_dm', models.IntegerField(blank=True, null=True)),
                ('detected_since_dm', models.IntegerField(blank=True, null=True)),
                ('tobacco', models.IntegerField(blank=True, null=True)),
                ('alcohol', models.IntegerField(blank=True, null=True)),
                ('smoking', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('weight', models.CharField(blank=True, max_length=150, null=True)),
                ('bmi', models.CharField(blank=True, max_length=150, null=True)),
                ('sbp', models.CharField(blank=True, max_length=150, null=True)),
                ('dbp', models.CharField(blank=True, max_length=150, null=True)),
                ('fbs', models.CharField(blank=True, max_length=150, null=True)),
                ('ppbs', models.CharField(blank=True, max_length=150, null=True)),
                ('rbs', models.CharField(blank=True, max_length=150, null=True)),
                ('symptoms', models.CharField(blank=True, max_length=150, null=True)),
                ('remarks', models.CharField(blank=True, max_length=150, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
