# Generated by Django 4.1.7 on 2023-04-25 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0047_clinicprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='phone_number',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits', regex='\\d{10}$')]),
        ),
    ]
