# Generated by Django 4.1.7 on 2023-04-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0047_clinicprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicprofile',
            name='detected_since_dm',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='clinicprofile',
            name='detected_since_htn',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
