# Generated by Django 4.1.7 on 2023-05-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0049_rename_date_clinicprofile_visit_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicprofile',
            name='height',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
