# Generated by Django 4.1.7 on 2023-05-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0051_alter_clinicprofile_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicprofile',
            name='remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
