# Generated by Django 4.1.7 on 2023-05-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0052_alter_clinicprofile_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatments',
            name='remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
