# Generated by Django 4.1.7 on 2023-05-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0054_alter_patients_height_alter_patients_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
