# Generated by Django 4.1.7 on 2023-05-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0055_alter_patients_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatments',
            name='co_morbid_names',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
