# Generated by Django 4.1.7 on 2023-05-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0056_alter_treatments_co_morbid_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='detected_years',
            field=models.DateField(blank=True, null=True),
        ),
    ]
