# Generated by Django 4.1.7 on 2023-05-22 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0057_diagnosis_detected_years'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='years',
        ),
    ]
