# Generated by Django 4.2.2 on 2023-06-19 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health_management', '0058_remove_diagnosis_years'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active')], db_index=True, default=2)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('sync_status', models.PositiveIntegerField(default=2)),
                ('uuid', models.CharField(blank=True, max_length=150, null=True)),
                ('user_uuid', models.CharField(blank=True, max_length=150, null=True)),
                ('patient_uuid', models.CharField(blank=True, max_length=150, null=True)),
                ('hyper_diabetic', models.PositiveIntegerField(default=0)),
                ('co_morbid_ids', models.CharField(blank=True, max_length=150, null=True)),
                ('co_morbid_names', models.CharField(blank=True, max_length=500, null=True)),
                ('is_alcoholic', models.CharField(blank=True, max_length=150, null=True)),
                ('is_tobacco', models.CharField(blank=True, max_length=150, null=True)),
                ('is_smoker', models.CharField(blank=True, max_length=150, null=True)),
                ('dm_check', models.IntegerField(default=0)),
                ('ht_check', models.IntegerField(default=0)),
                ('dm_status', models.IntegerField(default=0)),
                ('ht_status', models.IntegerField(default=0)),
                ('dm_source_treatment', models.CharField(blank=True, max_length=150, null=True)),
                ('ht_source_treatment', models.CharField(blank=True, max_length=150, null=True)),
                ('dm_years', models.CharField(blank=True, max_length=150, null=True)),
                ('ht_years', models.CharField(blank=True, max_length=150, null=True)),
                ('dm_detected_by', models.CharField(blank=True, max_length=150, null=True)),
                ('ht_detected_by', models.CharField(blank=True, max_length=150, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
