# Generated by Django 4.2.2 on 2023-06-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0059_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='dm_detected_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='health',
            name='dm_source_treatment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='health',
            name='ht_detected_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='health',
            name='ht_source_treatment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='health',
            name='is_alcoholic',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='health',
            name='is_smoker',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='is_tobacco',
            field=models.IntegerField(default=0),
        ),
    ]
