# Generated by Django 4.2.2 on 2023-06-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0060_alter_health_dm_detected_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='dm_years',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='ht_years',
            field=models.DateField(blank=True, null=True),
        ),
    ]
