# Generated by Django 4.2.2 on 2023-06-22 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0062_alter_health_hyper_diabetic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatments',
            name='co_morbid_ids',
        ),
        migrations.RemoveField(
            model_name='treatments',
            name='co_morbid_names',
        ),
        migrations.RemoveField(
            model_name='treatments',
            name='hyper_diabetic',
        ),
        migrations.RemoveField(
            model_name='treatments',
            name='is_alcoholic',
        ),
        migrations.RemoveField(
            model_name='treatments',
            name='is_smoker',
        ),
        migrations.RemoveField(
            model_name='treatments',
            name='is_tobacco',
        ),
    ]
