# Generated by Django 4.2.2 on 2023-06-22 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0063_remove_treatments_co_morbid_ids_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='last_visit_date',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='weight',
        ),
    ]
