# Generated by Django 4.2.2 on 2023-06-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0067_alter_patients_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayement',
            name='user_uuid',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
