# Generated by Django 4.2.2 on 2023-06-22 09:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0070_alter_diagnosis_uuid_alter_health_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayement',
            name='uuid',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='homevisit',
            name='uuid',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uuid',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=200, null=True, unique=True),
        ),
    ]
