# Generated by Django 4.2.2 on 2023-06-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0071_alter_feepayement_uuid_alter_homevisit_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='user_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
    ]
