# Generated by Django 4.2.2 on 2023-06-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0073_alter_patients_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='patient_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='user_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='feepayement',
            name='patient_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='feepayement',
            name='user_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='homevisit',
            name='patient_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='homevisit',
            name='user_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='treatment_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='user_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='scanned_report',
            name='patient_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='scanned_report',
            name='user_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='patient_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='user_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
    ]
