# Generated by Django 4.2.2 on 2023-06-22 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0074_alter_diagnosis_patient_uuid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feepayement',
            old_name='payment_date',
            new_name='fee_date',
        ),
    ]
