# Generated by Django 4.2.2 on 2023-06-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0076_rename_fee_date_feepayement_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='uuid',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='visit_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
