# Generated by Django 4.2.2 on 2023-06-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0083_alter_homevisit_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='patient_uuid',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
