# Generated by Django 4.2.2 on 2023-11-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0089_healthprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
