# Generated by Django 4.2.2 on 2024-01-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0092_health_dm_year_health_ht_year_health_pdm_detected_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthprofile',
            name='detected_since_dm',
            field=models.DateField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='detected_since_ht',
            field=models.DateField(blank=True, null=True),
        ),
    ]
