# Generated by Django 4.2.2 on 2024-01-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0093_alter_healthprofile_detected_since_dm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='co_morbidities',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='hyper_diabetic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='is_alcoholic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='is_smoker',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='is_tobacco',
            field=models.IntegerField(default=0),
        ),
    ]
