# Generated by Django 4.2.2 on 2024-02-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0094_healthprofile_co_morbidities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='patient_id',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
    ]
