# Generated by Django 4.2.2 on 2024-02-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0095_alter_patients_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatments',
            name='source_treatment',
            field=models.IntegerField(blank=True, choices=[(1, 'CLINIC'), (2, 'OUTSIDE'), (3, 'C & O'), (4, 'NOT')], null=True),
        ),
    ]
