# Generated by Django 4.2.2 on 2024-02-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_management', '0096_treatments_source_treatment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatments',
            old_name='source_treatment',
            new_name='dm_source_treatment',
        ),
        migrations.AddField(
            model_name='treatments',
            name='ht_source_treatment',
            field=models.IntegerField(blank=True, choices=[(1, 'CLINIC'), (2, 'OUTSIDE'), (3, 'C & O'), (4, 'NOT')], null=True),
        ),
    ]
